
name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    runs-on: ubuntu-latest
    name: build release
    env:
      SQLX_OFFLINE: true
    defaults:
      run:
        working-directory: .
    container:
      image: clux/muslrust
    steps:
    - uses: actions/checkout@v2
    - name: Link to predefined musl toolchain
      run: |
          ln -s /root/.cargo $HOME/.cargo
          ln -s /root/.rustup $HOME/.rustup
    
    - name: Build
      run: cargo build --release
    - name: Print Dir
      run: |
        ls
        cd ./target 
        ls
        cd ./release
        ls
        cd ./build
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: Build test
        path: ./target/x86_64-unknown-linux-musl/release/
